version: '2'
services:
  web:
    build: .
    ports:
      - "80:5000"
    volumes:
      - ./:/opt/objects-api
    links:
      - db:mongodb
    container_name: objectsapi_web_1
  db:
    image: mongo:3.0.2
    container_name: objectsapi_db_1